// Based on:
// https://github.com/shaderwitch/AssetEditorTemplate

#include "Viewport/SplineToolkitRulesetEditorPreviewScene.h"

#include "SplineToolkitInstantiator.h"
#include "SplineToolkitMeshExtruder.h"
#include "SplineToolkitMeshStretcher.h"
#include "Components/SplineComponent.h"
#include "GameFramework/WorldSettings.h"
#include "Viewport/SplineToolkitRulesetEditorViewport.h"


namespace
{

/// Previews generated by Claude since they have to be hard coded.
/// (Could try making them manually later if I have time)
#pragma region Previews

TArray<FVector> SBendPoints = {
	FVector(0.f, 0.f, 0.f),
	FVector(1000.f, 500.f, 0.f),
	FVector(2000.f, 0.f, 0.f),
	FVector(3000.f, -500.f, 0.f),
	FVector(4000.f, 0.f, 0.f)
};

TArray<FVector> SBendTangents = {
	FVector(1500.f, 0.f, 0.f),
	FVector(1500.f, 0.f, 0.f),
	FVector(1500.f, 0.f, 0.f),
	FVector(1500.f, 0.f, 0.f),
	FVector(1500.f, 0.f, 0.f)
};

TArray<FVector> LoopPoints = {
	FVector(0.f, 0.f, 0.f), // start
	FVector(500.f, 0.f, 0.f), // approach
	FVector(900.f, 0.f, 0.f), // loop bottom (entry)
	FVector(1183.f, 0.f, 117.f),
	FVector(1300.f, 0.f, 400.f), // loop side
	FVector(1183.f, 0.f, 683.f),
	FVector(900.f, 0.f, 800.f), // top of loop
	FVector(617.f, 0.f, 683.f),
	FVector(500.f, 0.f, 400.f), // loop side
	FVector(617.f, 0.f, 117.f),
	FVector(900.f, 0.f, 0.f), // loop bottom (exit)
	FVector(1300.f, 0.f, 0.f) // exit straight
};

TArray<FVector> LoopTangents = {
	FVector(300.f, 0.f, 0.f),
	FVector(300.f, 0.f, 0.f),
	FVector(300.f, 0.f, 0.f),
	FVector(212.f, 0.f, 212.f),
	FVector(0.f, 0.f, 300.f),
	FVector(-212.f, 0.f, 212.f),
	FVector(-300.f, 0.f, 0.f),
	FVector(-212.f, 0.f, -212.f),
	FVector(0.f, 0.f, -300.f),
	FVector(212.f, 0.f, -212.f),
	FVector(300.f, 0.f, 0.f),
	FVector(300.f, 0.f, 0.f)
};

TArray<FVector> TrackPoints = {
	// Long straight
	FVector(0.f, 0.f, 0.f),
	FVector(2000.f, 0.f, 0.f),

	// Tight curve (90°, small radius ~250)
	FVector(2180.f, 75.f, 0.f),
	FVector(2250.f, 250.f, 0.f),

	// Short straight
	FVector(2250.f, 650.f, 0.f),

	// Wide S-bend (large radius, bulging in X while advancing in Y)
	FVector(2750.f, 1250.f, 0.f),
	FVector(2250.f, 1850.f, 0.f),
	FVector(1750.f, 2450.f, 0.f),
	FVector(2250.f, 3050.f, 0.f),

	// Hairpin (tight ~180° reversal, radius ~250)
	FVector(2320.f, 3230.f, 0.f),
	FVector(2500.f, 3300.f, 0.f), // apex
	FVector(2680.f, 3230.f, 0.f),
	FVector(2750.f, 3050.f, 0.f), // exit, heading now reversed

	// Little slope up (climbing while heading back toward the start)
	FVector(2200.f, 2300.f, 500.f),

	// Final straight, passing directly over the first long straight
	FVector(950.f, 0.f, 700.f), // X=950 sits inside the 0–2000 range of the first straight, Z=700 elevates it above
	FVector(100.f, -500.f, 700.f)
};

TArray<FVector> TrackTangents = {
	// Long straight
	FVector(800.f, 0.f, 0.f),
	FVector(800.f, 0.f, 0.f),

	// Tight curve
	FVector(500.f, 500.f, 0.f),
	FVector(0.f, 600.f, 0.f),

	// Short straight
	FVector(0.f, 600.f, 0.f),

	// Wide S-bend (constant forward-axis tangent — same trick as the flat S-bend, lets the bulges read smoothly)
	FVector(0.f, 900.f, 0.f),
	FVector(0.f, 900.f, 0.f),
	FVector(0.f, 900.f, 0.f),
	FVector(0.f, 300.f, 0.f),

	// Hairpin
	FVector(250.f, 250.f, 0.f),
	FVector(350.f, 0.f, 0.f),
	FVector(250.f, -250.f, 0.f),
	FVector(0.f, -300.f, 0.f),

	// Slope up + final straight (one continuous direction — this is what keeps it a genuine "straight", no curvature)
	FVector(-700.f, -1200.f, 250.f),
	FVector(-700.f, -1200.f, 250.f),
	FVector(-700.f, -1200.f, 250.f)
};

#pragma endregion

void SetSplinePointsWithTangents(USplineComponent* SplineComponent, const TArray<FVector>& Points,
                                 const TArray<FVector>& Tangents)
{
	if (!SplineComponent || Points.Num() != Tangents.Num() || Points.Num() == 0)
	{
		return;
	}

	SplineComponent->ClearSplinePoints(false);

	for (const FVector& Point : Points)
	{
		SplineComponent->AddSplinePoint(Point, ESplineCoordinateSpace::Local, false);
	}

	for (int32 i = 0; i < Points.Num(); ++i)
	{
		SplineComponent->SetTangentAtSplinePoint(i, Tangents[i], ESplineCoordinateSpace::Local, false);
	}

	SplineComponent->UpdateSpline();
}

}


FSplineToolkitRulesetPreviewScene::FSplineToolkitRulesetPreviewScene(ConstructionValues CVS,
                                                                     const TSharedRef<
	                                                                     FSplineToolkitRulesetEditorToolkit>&
                                                                     EditorToolkit)
	: FAdvancedPreviewScene(CVS)
	  , EditorPtr(EditorToolkit)
{
	// Disable killing actors outside of the world
	AWorldSettings* WorldSettings = GetWorld()->GetWorldSettings(true);
	WorldSettings->bEnableWorldBoundsChecks = false;
	
	UObject* Ruleset = GetEditor()->GetRuleset();
	
	// Auto update preview
	FCoreUObjectDelegates::OnObjectPropertyChanged.AddLambda([this, Ruleset](UObject* Obj, FPropertyChangedEvent&)
	{
		if (Obj != Ruleset) return;
		UpdatePreview();
	});

	//Hide default floor
	SetFloorVisibility(false, false);

	UpdateSplinePreview(SplinePreview::Track);
}


FSplineToolkitRulesetPreviewScene::~FSplineToolkitRulesetPreviewScene()
{
}


void FSplineToolkitRulesetPreviewScene::Tick(float InDeltaTime)
{
	FAdvancedPreviewScene::Tick(InDeltaTime);
	GetWorld()->Tick(LEVELTICK_All, InDeltaTime);
}


void FSplineToolkitRulesetPreviewScene::UpdateSplinePreview(SplinePreview preview)
{
	// Delete old actors
	for (const auto& Actor : PreviewActors)
	{
		if (!Actor.IsResolved() || !Actor->IsValidLowLevel()) continue;
		Actor->Destroy();
	}
	PreviewActors.Empty();

	// Create the first actor
	AActor* Spline0 = GetWorld()->SpawnActor<AActor>();
	PreviewActors.Add(Spline0);

	// Create the spline
	auto* Spline = reinterpret_cast<USplineComponent*>(Spline0->AddComponentByClass(
		USplineComponent::StaticClass(), false, FTransform::Identity, false));
	Spline->RegisterComponent();

	// Set points and tangents
	switch (preview)
	{
	case SplinePreview::Track:
		SetSplinePointsWithTangents(Spline, TrackPoints, TrackTangents);
		break;
	case SplinePreview::Loop:
		SetSplinePointsWithTangents(Spline, LoopPoints, LoopTangents);
		break;
	case SplinePreview::SBend:
		SetSplinePointsWithTangents(Spline, SBendPoints, SBendTangents);
		break;
	}

	// Add RMF sampler
	auto* RmfSampler = reinterpret_cast<USplineToolkitRmfSampler*>(Spline0->AddComponentByClass(
		USplineToolkitRmfSampler::StaticClass(), false, FTransform::Identity, false));
	RmfSampler->RegisterComponent();

	// Add instantiator and set the ruleset
	auto* Instantiator = reinterpret_cast<USplineToolkitInstantiator*>(Spline0->AddComponentByClass(
		USplineToolkitInstantiator::StaticClass(), false, FTransform::Identity, false));
	Instantiator->RegisterComponent();
	Instantiator->Ruleset = GetEditor()->GetRuleset();

	// Add extruder and set the ruleset
	auto* Extruder = reinterpret_cast<USplineToolkitMeshExtruder*>(Spline0->AddComponentByClass(
		USplineToolkitMeshExtruder::StaticClass(), false, FTransform::Identity, false));
	Extruder->RegisterComponent();
	Extruder->Ruleset = GetEditor()->GetRuleset();

	auto* Stretcher = reinterpret_cast<USplineToolkitMeshStretcher*>(Spline0->AddComponentByClass(
		USplineToolkitMeshStretcher::StaticClass(), false, FTransform::Identity, false));
	Stretcher->RegisterComponent();
	Stretcher->Ruleset = GetEditor()->GetRuleset();

	// TODO: Add the other components
	
	
	UpdatePreview();
}


void FSplineToolkitRulesetPreviewScene::UpdatePreview()
{
	if (!AutoUpdate) return;
	
	for (auto Actor : PreviewActors)
	{
		if (!Actor.IsResolved() || !Actor->IsValidLowLevel()) continue;
		if (auto* RmfSampler = Actor->GetComponentByClass<USplineToolkitRmfSampler>())
			RmfSampler->Regenerate();

		if (auto* Instantiator = Actor->GetComponentByClass<USplineToolkitInstantiator>())
			Instantiator->Regenerate();

		if (auto* Extruder = Actor->GetComponentByClass<USplineToolkitMeshExtruder>())
			Extruder->Regenerate();
		
		if (auto* Stretcher = Actor->GetComponentByClass<USplineToolkitMeshStretcher>())
			Stretcher->Regenerate();
		
		// TODO: Add the other components
	}
}


void FSplineToolkitRulesetPreviewScene::SetPreviewSpline(const SplinePreview Preview)
{
	CurrentPreview = Preview;
	UpdateSplinePreview(Preview);
}
